let data =
{
    "Date": "2022-07-02T11:30:00+03:00",
    "PreviousDate": "2022-07-01T11:30:00+03:00",
    "PreviousURL": "\/\/www.cbr-xml-daily.ru\/archive\/2022\/07\/01\/daily_json.js",
    "Timestamp": "2022-07-04T12:00:00+03:00",
    "Valute": {
        "AUD": {
            "ID": "R01010",
            "NumCode": "036",
            "CharCode": "AUD",
            "Nominal": 1,
            "Name": "Австралийский доллар",
            "Value": 36.7233,
            "Previous": 36.1757
        },
        "AZN": {
            "ID": "R01020A",
            "NumCode": "944",
            "CharCode": "AZN",
            "Nominal": 1,
            "Name": "Азербайджанский манат",
            "Value": 31.628,
            "Previous": 30.8896
        },
        "GBP": {
            "ID": "R01035",
            "NumCode": "826",
            "CharCode": "GBP",
            "Nominal": 1,
            "Name": "Фунт стерлингов Соединенного королевства",
            "Value": 65.29,
            "Previous": 63.6502
        },
        "AMD": {
            "ID": "R01060",
            "NumCode": "051",
            "CharCode": "AMD",
            "Nominal": 100,
            "Name": "Армянских драмов",
            "Value": 13.1799,
            "Previous": 12.8956
        },
        "BYN": {
            "ID": "R01090B",
            "NumCode": "933",
            "CharCode": "BYN",
            "Nominal": 1,
            "Name": "Белорусский рубль",
            "Value": 20.9514,
            "Previous": 20.4623
        },
        "BGN": {
            "ID": "R01100",
            "NumCode": "975",
            "CharCode": "BGN",
            "Nominal": 1,
            "Name": "Болгарский лев",
            "Value": 28.5542,
            "Previous": 28.237
        },
        "BRL": {
            "ID": "R01115",
            "NumCode": "986",
            "CharCode": "BRL",
            "Nominal": 1,
            "Name": "Бразильский реал",
            "Value": 10.2655,
            "Previous": 10.0473
        },
        "HUF": {
            "ID": "R01135",
            "NumCode": "348",
            "CharCode": "HUF",
            "Nominal": 100,
            "Name": "Венгерских форинтов",
            "Value": 14.1033,
            "Previous": 13.8194
        },
        "HKD": {
            "ID": "R01200",
            "NumCode": "344",
            "CharCode": "HKD",
            "Nominal": 10,
            "Name": "Гонконгских долларов",
            "Value": 68.6424,
            "Previous": 67.0484
        },
        "DKK": {
            "ID": "R01215",
            "NumCode": "208",
            "CharCode": "DKK",
            "Nominal": 10,
            "Name": "Датских крон",
            "Value": 75.0734,
            "Previous": 74.2381
        },
        "USD": {
            "ID": "R01235",
            "NumCode": "840",
            "CharCode": "USD",
            "Nominal": 1,
            "Name": "Доллар США",
            "Value": 53.7676,
            "Previous": 52.5123
        },
        "EUR": {
            "ID": "R01239",
            "NumCode": "978",
            "CharCode": "EUR",
            "Nominal": 1,
            "Name": "Евро",
            "Value": 56.3584,
            "Previous": 54.6405
        },
        "INR": {
            "ID": "R01270",
            "NumCode": "356",
            "CharCode": "INR",
            "Nominal": 100,
            "Name": "Индийских рупий",
            "Value": 68.6417,
            "Previous": 67.0945
        },
        "KZT": {
            "ID": "R01335",
            "NumCode": "398",
            "CharCode": "KZT",
            "Nominal": 100,
            "Name": "Казахстанских тенге",
            "Value": 11.4316,
            "Previous": 11.291
        },
        "CAD": {
            "ID": "R01350",
            "NumCode": "124",
            "CharCode": "CAD",
            "Nominal": 1,
            "Name": "Канадский доллар",
            "Value": 41.7256,
            "Previous": 40.7768
        },
        "KGS": {
            "ID": "R01370",
            "NumCode": "417",
            "CharCode": "KGS",
            "Nominal": 100,
            "Name": "Киргизских сомов",
            "Value": 67.6322,
            "Previous": 66.0532
        },
        "CNY": {
            "ID": "R01375",
            "NumCode": "156",
            "CharCode": "CNY",
            "Nominal": 10,
            "Name": "Китайских юаней",
            "Value": 85.9418,
            "Previous": 82.8897
        },
        "MDL": {
            "ID": "R01500",
            "NumCode": "498",
            "CharCode": "MDL",
            "Nominal": 10,
            "Name": "Молдавских леев",
            "Value": 28.1439,
            "Previous": 27.4623
        },
        "NOK": {
            "ID": "R01535",
            "NumCode": "578",
            "CharCode": "NOK",
            "Nominal": 10,
            "Name": "Норвежских крон",
            "Value": 54.0258,
            "Previous": 52.7529
        },
        "PLN": {
            "ID": "R01565",
            "NumCode": "985",
            "CharCode": "PLN",
            "Nominal": 1,
            "Name": "Польский злотый",
            "Value": 11.8839,
            "Previous": 11.6381
        },
        "RON": {
            "ID": "R01585F",
            "NumCode": "946",
            "CharCode": "RON",
            "Nominal": 1,
            "Name": "Румынский лей",
            "Value": 11.3707,
            "Previous": 11.0729
        },
        "XDR": {
            "ID": "R01589",
            "NumCode": "960",
            "CharCode": "XDR",
            "Nominal": 1,
            "Name": "СДР (специальные права заимствования)",
            "Value": 71.3915,
            "Previous": 69.9926
        },
        "SGD": {
            "ID": "R01625",
            "NumCode": "702",
            "CharCode": "SGD",
            "Nominal": 1,
            "Name": "Сингапурский доллар",
            "Value": 38.6012,
            "Previous": 37.7298
        },
        "TJS": {
            "ID": "R01670",
            "NumCode": "972",
            "CharCode": "TJS",
            "Nominal": 10,
            "Name": "Таджикских сомони",
            "Value": 50.8859,
            "Previous": 49.7379
        },
        "TRY": {
            "ID": "R01700J",
            "NumCode": "949",
            "CharCode": "TRY",
            "Nominal": 10,
            "Name": "Турецких лир",
            "Value": 32.2417,
            "Previous": 31.4745
        },
        "TMT": {
            "ID": "R01710A",
            "NumCode": "934",
            "CharCode": "TMT",
            "Nominal": 1,
            "Name": "Новый туркменский манат",
            "Value": 15.3622,
            "Previous": 15.0035
        },
        "UZS": {
            "ID": "R01717",
            "NumCode": "860",
            "CharCode": "UZS",
            "Nominal": 10000,
            "Name": "Узбекских сумов",
            "Value": 49.4827,
            "Previous": 48.3528
        },
        "UAH": {
            "ID": "R01720",
            "NumCode": "980",
            "CharCode": "UAH",
            "Nominal": 10,
            "Name": "Украинских гривен",
            "Value": 18.2867,
            "Previous": 17.7865
        },
        "CZK": {
            "ID": "R01760",
            "NumCode": "203",
            "CharCode": "CZK",
            "Nominal": 10,
            "Name": "Чешских крон",
            "Value": 22.5715,
            "Previous": 22.3248
        },
        "SEK": {
            "ID": "R01770",
            "NumCode": "752",
            "CharCode": "SEK",
            "Nominal": 10,
            "Name": "Шведских крон",
            "Value": 52.2497,
            "Previous": 51.3849
        },
        "CHF": {
            "ID": "R01775",
            "NumCode": "756",
            "CharCode": "CHF",
            "Nominal": 1,
            "Name": "Швейцарский франк",
            "Value": 56.119,
            "Previous": 54.9464
        },
        "ZAR": {
            "ID": "R01810",
            "NumCode": "710",
            "CharCode": "ZAR",
            "Nominal": 10,
            "Name": "Южноафриканских рэндов",
            "Value": 32.889,
            "Previous": 32.3131
        },
        "KRW": {
            "ID": "R01815",
            "NumCode": "410",
            "CharCode": "KRW",
            "Nominal": 1000,
            "Name": "Вон Республики Корея",
            "Value": 41.4458,
            "Previous": 40.4439
        },
        "JPY": {
            "ID": "R01820",
            "NumCode": "392",
            "CharCode": "JPY",
            "Nominal": 100,
            "Name": "Японских иен",
            "Value": 39.5408,
            "Previous": 38.4339
        }
    }
}


const countryData = {

    "Country": {
        "AU": { "Valute": "AUD" },
        "AT": { "Valute": "EUR" },
        "AZ": { "Valute": "AZM" },
        "A2": { "Valute": "EUR" },
        "AX": { "Valute": "EUR" },
        "AL": { "Valute": "EUR" },
        "DZ": { "Valute": "DZD" },
        "AS": { "Valute": "USD" },
        "AI": { "Valute": "XCD" },
        "EN": { "Valute": "GBP" },
        "AO": { "Valute": "AOA" },
        "AD": { "Valute": "EUR" },
        "AG": { "Valute": "XCD" },
        "AR": { "Valute": "ARS" },
        "AM": { "Valute": "AMD" },
        "AW": { "Valute": "AWG" },
        "AF": { "Valute": "USD" },
        "BS": { "Valute": "BSD" },
        "BD": { "Valute": "BDT" },
        "BB": { "Valute": "BBD" },
        "BH": { "Valute": "BHD" },
        "BZ": { "Valute": "BZD" },
        "BY": { "Valute": "BYR" },
        "BE": { "Valute": "EUR" },
        "BJ": { "Valute": "XOF" },
        "BM": { "Valute": "BMD" },
        "BG": { "Valute": "EUR" },
        "BO": { "Valute": "BOB" },
        "BA": { "Valute": "BAM" },
        "BW": { "Valute": "BWP" },
        "BR": { "Valute": "BRL" },
        "VG": { "Valute": "USD" },
        "BN": { "Valute": "BND" },
        "BF": { "Valute": "XOF" },
        "BI": { "Valute": "BIF" },
        "BT": { "Valute": "BTN" },
        "VU": { "Valute": "VUV" },
        "HU": { "Valute": "HUF" },
        "VE": { "Valute": "VEB" },
        "VR": { "Valute": "USD" },
        "TL": { "Valute": "USD" },
        "VN": { "Valute": "VND" },
        "GA": { "Valute": "XAF" },
        "GY": { "Valute": "GYD" },
        "HT": { "Valute": "HTG" },
        "GM": { "Valute": "GMD" },
        "GH": { "Valute": "GHS" },
        "GP": { "Valute": "EUR" },
        "GT": { "Valute": "GTQ" },
        "GN": { "Valute": "GNF" },
        "GW": { "Valute": "XOF" },
        "DE": { "Valute": "EUR" },
        "GG": { "Valute": "GBP" },
        "GI": { "Valute": "GIP" },
        "HO": { "Valute": "EUR" },
        "HN": { "Valute": "HNL" },
        "HK": { "Valute": "HKD" },
        "VA": { "Valute": "EUR" },
        "GD": { "Valute": "XCD" },
        "GL": { "Valute": "DKK" },
        "GR": { "Valute": "EUR" },
        "GE": { "Valute": "GEL" },
        "GU": { "Valute": "USD" },
        "DK": { "Valute": "DKK" },
        "CD": { "Valute": "CDF" },
        "JE": { "Valute": "GBP" },
        "DJ": { "Valute": "DJF" },
        "DM": { "Valute": "XCD" },
        "DO": { "Valute": "DOP" },
        "EP": { "Valute": "EUR" },
        "EG": { "Valute": "EGP" },
        "ZM": { "Valute": "ZMK" },
        "ZW": { "Valute": "ZWD" },
        "YE": { "Valute": "YER" },
        "IL": { "Valute": "ILS" },
        "IN": { "Valute": "INR" },
        "ID": { "Valute": "IDR" },
        "JO": { "Valute": "JOD" },
        "IQ": { "Valute": "NID" },
        "IE": { "Valute": "EUR" },
        "IS": { "Valute": "ISK" },
        "ES": { "Valute": "EUR" },
        "IT": { "Valute": "EUR" },
        "KZ": { "Valute": "KZT" },
        "KY": { "Valute": "KYD" },
        "KH": { "Valute": "KHR" },
        "CM": { "Valute": "XAF" },
        "CA": { "Valute": "CAD" },
        "IC": { "Valute": "EUR" },
        "QA": { "Valute": "QAR" },
        "KE": { "Valute": "KES" },
        "CY": { "Valute": "EUR" },
        "KG": { "Valute": "KGS" },
        "KI": { "Valute": "AUD" },
        "CN": { "Valute": "RMB" },
        "CO": { "Valute": "COP" },
        "KM": { "Valute": "USD" },
        "CG": { "Valute": "XAF" },
        "KV": { "Valute": "EUR" },
        "KO": { "Valute": "USD" },
        "CR": { "Valute": "CRC" },
        "CI": { "Valute": "XOF" },
        "CU": { "Valute": "CU" },
        "KW": { "Valute": "KWD" },
        "CW": { "Valute": "USD" },
        "LA": { "Valute": "LAK" },
        "LV": { "Valute": "EUR" },
        "LS": { "Valute": "LSL" },
        "LR": { "Valute": "LRD" },
        "LB": { "Valute": "LBP" },
        "LY": { "Valute": "LYD" },
        "LT": { "Valute": "EUR" },
        "LI": { "Valute": "CHF" },
        "LU": { "Valute": "EUR" },
        "MU": { "Valute": "MUR" },
        "MR": { "Valute": "MRO" },
        "MG": { "Valute": "MGA" },
        "M3": { "Valute": "EUR" },
        "YT": { "Valute": "EUR" },
        "MO": { "Valute": "MOP" },
        "MK": { "Valute": "EUR" },
        "MW": { "Valute": "MWK" },
        "MY": { "Valute": "MYR" },
        "ML": { "Valute": "XOF" },
        "MV": { "Valute": "MVR" },
        "MT": { "Valute": "EUR" },
        "MA": { "Valute": "MAD" },
        "MQ": { "Valute": "EUR" },
        "MH": { "Valute": "USD" },
        "MX": { "Valute": "MXN" },
        "XL": { "Valute": "EUR" },
        "MZ": { "Valute": "MZM" },
        "MD": { "Valute": "MDL" },
        "MC": { "Valute": "EUR" },
        "MN": { "Valute": "MNT" },
        "MS": { "Valute": "XCD" },
        "NA": { "Valute": "NAD" },
        "NP": { "Valute": "NPR" },
        "NE": { "Valute": "XOF" },
        "NG": { "Valute": "NGN" },
        "NL": { "Valute": "EUR" },
        "NI": { "Valute": "NIO" },
        "NZ": { "Valute": "NZD" },
        "NC": { "Valute": "XPF" },
        "NO": { "Valute": "NOK" },
        "BQ": { "Valute": "USD" },
        "AE": { "Valute": "AED" },
        "BL": { "Valute": "EUR" },
        "E2": { "Valute": "ANG" },
        "C3": { "Valute": "USD" },
        "WF": { "Valute": "XPF" },
        "OM": { "Valute": "OMR" },
        "NF": { "Valute": "AUD" },
        "CV": { "Valute": "CVE" },
        "CK": { "Valute": "NZD" },
        "UI": { "Valute": "XCD" },
        "PK": { "Valute": "PKR" },
        "PW": { "Valute": "USD" },
        "PA": { "Valute": "PAB" },
        "PG": { "Valute": "PGK" },
        "PY": { "Valute": "PYG" },
        "PE": { "Valute": "PEN" },
        "PL": { "Valute": "PLN" },
        "PO": { "Valute": "USD" },
        "PT": { "Valute": "EUR" },
        "PR": { "Valute": "USD" },
        "RE": { "Valute": "EUR" },
        "RU": { "Valute": "RUR" },
        "RT": { "Valute": "USD" },
        "RW": { "Valute": "RWF" },
        "RO": { "Valute": "ROL" },
        "S1": { "Valute": "ANG" },
        "SP": { "Valute": "USD" },
        "WS": { "Valute": "WST" },
        "SM": { "Valute": "EUR" },
        "ST": { "Valute": "STD" },
        "SA": { "Valute": "SAR" },
        "SZ": { "Valute": "SZL" },
        "NB": { "Valute": "GBP" },
        "MP": { "Valute": "USD" },
        "SC": { "Valute": "SCR" },
        "SN": { "Valute": "XOF" },
        "VC": { "Valute": "XCD" },
        "UV": { "Valute": "USD" },
        "KN": { "Valute": "XCD" },
        "SW": { "Valute": "XCD" },
        "LC": { "Valute": "XCD" },
        "SX": { "Valute": "USD" },
        "VL": { "Valute": "USD" },
        "RS": { "Valute": "EUR" },
        "XC": { "Valute": "EUR" },
        "SG": { "Valute": "SGD" },
        "SK": { "Valute": "EUR" },
        "SI": { "Valute": "EUR" },
        "GB": { "Valute": "GBP" },
        "US": { "Valute": "USD" },
        "SB": { "Valute": "SBD" },
        "SR": { "Valute": "SRG" },
        "VI": { "Valute": "USD" },
        "SL": { "Valute": "SLL" },
        "TJ": { "Valute": "TJS" },
        "TW": { "Valute": "TWD" },
        "TH": { "Valute": "THB" },
        "TA": { "Valute": "XPF" },
        "TZ": { "Valute": "TZS" },
        "TC": { "Valute": "USD" },
        "TI": { "Valute": "USD" },
        "TG": { "Valute": "XOF" },
        "TO": { "Valute": "TOP" },
        "ZZ": { "Valute": "USD" },
        "TT": { "Valute": "TTD" },
        "TU": { "Valute": "USD" },
        "TV": { "Valute": "AUD" },
        "TN": { "Valute": "TND" },
        "TM": { "Valute": "TMT" },
        "TR": { "Valute": "TRY" },
        "UG": { "Valute": "UGX" },
        "UZ": { "Valute": "UZS" },
        "UA": { "Valute": "UAH" },
        "UY": { "Valute": "UYU" },
        "WL": { "Valute": "GBP" },
        "FO": { "Valute": "DKK" },
        "FM": { "Valute": "USD" },
        "FJ": { "Valute": "FJD" },
        "PH": { "Valute": "PHP" },
        "FI": { "Valute": "EUR" },
        "FR": { "Valute": "EUR" },
        "GF": { "Valute": "EUR" },
        "PF": { "Valute": "XPF" },
        "HR": { "Valute": "EUR" },
        "CF": { "Valute": "XAF" },
        "TD": { "Valute": "XAF" },
        "ME": { "Valute": "EUR" },
        "CZ": { "Valute": "CZK" },
        "CL": { "Valute": "CLP" },
        "CH": { "Valute": "CHF" },
        "SE": { "Valute": "SEK" },
        "SF": { "Valute": "GBP" },
        "LK": { "Valute": "LKR" },
        "EC": { "Valute": "USD" },
        "GQ": { "Valute": "XAF" },
        "SV": { "Valute": "USD" },
        "ER": { "Valute": "ERN" },
        "EE": { "Valute": "EUR" },
        "ET": { "Valute": "ETB" },
        "ZA": { "Valute": "ZAR" },
        "KR": { "Valute": "KRW" },
        "JM": { "Valute": "JMD" },
        "YA": { "Valute": "USD" },
        "JP": { "Valute": "JPY" },
    }
}

export { countryData }